build_and_test_gcc:
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
build_and_test_clang:
  script:
    - mkdir build
    - cd build
    - CC=clang CXX=clang++ cmake ..
    - make
    - make test

