name: windows-msvc

on:
  push:
    branches:
      - master
    paths-ignore:
        - 'doc/**'
        - '**/*.md'
        - .travis.yml
        - .gitlab-ci.yml
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**/*.md'
      - .travis.yml
      - .gitlab-ci.yml

jobs:
  build:
    name: ci-windows-msvc-17
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Visual Studio Environment
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Cache Conan packages
        id: cache-conan
        uses: actions/cache@v4.0.2
        env:
          cache-name: cache-conan-packages
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('conanfile.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Configure python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        run: python -m pip install -r .github/requirements.txt

      - name: Configure Conan profile
        run: conan profile detect --force --name default

      - name: Install Conan dependencies
        run: |
          conan install conanfile.txt -r conancenter -s compiler.cppstd=17 -c tools.cmake.cmaketoolchain:generator=Ninja --build=missing

      - name: Configure CMake
        run: |
          cmake -S . --preset conan-release -G Ninja -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_INSTALL_PREFIX=install -DBUILD_TESTS:BOOL=ON

      - name: Build
        run: cmake --build --preset conan-release

      - name: Test
        run: cmake --build --preset conan-release --target test --output-on-failure

      - name: Install
        run: cmake --build --preset conan-release --target install
